language: python

python: 3.5
sudo: required

env:
  - TRAVIS_NODE_VERSION="6"

services:
    - mongodb
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    - elasticsearch-2.x
    - google-chrome
    packages:
    - mongodb-org-server
    - elasticsearch
    - google-chrome-stable

cache:
    - pip
    - npm

before_install:
    - sudo apt-get purge elasticsearch
    - sudo apt-get install -t stable elasticsearch && sudo service elasticsearch restart
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - node --version

install:
    - npm install --python=python2.7
    - cd server && pip install -r requirements.txt && cd ..
    - gem install coveralls-lcov
script:
    - make test
after_success:
    - coveralls-lcov -v -n coverage/lcov.info > coverage.json
    - coveralls --merge=coverage.json
